import GeminiIcon from "@/assets/icons/apps/gemini.svg"
import icloudIcon from "@/assets/icons/apps/icloud.svg"
import NetflixIcon from "@/assets/icons/apps/netflix.svg"
import SpotifyIcon from "@/assets/icons/apps/spotify.svg"
import YoutubeIcon from "@/assets/icons/apps/youtube.svg"

export const subscriptionData = [
  {
    id: "1",
    name: "Netflix",
    category: "Entertainment",
    plan: "Premium 4K",
    renewalDate: "Oct 12, 2026",
    price: 19.99,
    billing: "Monthly",
    icon: NetflixIcon,
    activeColor: "#ffffff",
    paymentMethod: "Visa",
    startDate: "05/07",
    status: false,
  },
  {
    id: "2",
    name: "Spotify",
    category: "Music",
    plan: "Duo Plan",
    renewalDate: "Oct 18, 2026",
    price: 14.99,
    billing: "Monthly",
    icon: SpotifyIcon,
    activeColor: "#14532d",
    paymentMethod: "Mastercard",
    startDate: "03/22",
    status: true,
  },
//   {
//     id: "3",
//     name: "Figma",
//     category: "Design Tools",
//     plan: "Professional",
//     renewalDate: "Nov 01, 2026",
//     price: 144.00,
//     billing: "Yearly",
//     icon: require("@/assets/images/Me.jpg"),
//     activeColor: "#431407",
//     paymentMethod: "Crypto",
//     startDate: "11/01",
//     status: true,
//   },
  {
    id: "4",
    name: "iCloud",
    category: "server Tools",
    plan: "All Apps",
    renewalDate: "Dec 15, 2026",
    price: 54.99,
    billing: "Monthly",
    icon: icloudIcon,
    activeColor: "#312e81",
    paymentMethod: "Visa",
    startDate: "01/15",
    status: false,
  },
  {
    id: "5",
    name: "Gemini",
    category: "Developer Tools",
    plan: "Individual",
    renewalDate: "Oct 05, 2026",
    price: 10.00,
    billing: "Monthly",
    icon: GeminiIcon,
    activeColor: "#18181b",
    paymentMethod: "Mastercard",
    startDate: "04/05",
    status: true,
  },
  {
    id: "6",
    name: "YouTube Premium",
    category: "Entertainment",
    plan: "Family",
    renewalDate: "Nov 20, 2026",
    price: 22.99,
    billing: "Monthly",
    icon: YoutubeIcon,
    activeColor: "#7f1d1d",
    paymentMethod: "Crypto",
    startDate: "02/20",
    status: false,
  },
];